cleanup e2e test makefile

diff --git a/tests/e2e/Makefile b/tests/e2e/Makefile
--- a/tests/e2e/Makefile
+++ b/tests/e2e/Makefile
@@ -3,8 +3,16 @@ SHELL = bash
 K8S_TEST_VERSION ?= v1.30.1
 GINKGO = bin/ginkgo
 GINKGO_ARGS = -v -nodes=4
-
 E2E = bin/e2e.test
+
+# Function to check if E2EKUBECONFIG is set
+define check_e2e_kubeconfig
+	@if [ -z "$(E2EKUBECONFIG)" ]; then \
+		echo "Error: E2EKUBECONFIG environment variable is not set"; \
+		echo "Please set E2EKUBECONFIG to the path of a kubeconfig file with a prepared cluster for e2e tests"; \
+		exit 1; \
+	fi
+endef
 
 bin:
 	mkdir -p bin
@@ -13,27 +21,30 @@ bin:
 			kubernetes/test/bin/e2e.test \
 			kubernetes/test/bin/ginkgo
 
-test-shared: bin
+test: bin
+	$(check_e2e_kubeconfig)
 	$(GINKGO) $(GINKGO_ARGS) \
 		--focus 'csi.xen-orchestra.marcsi.ch' \
 		--skip 'Disruptive' \
 		--skip "volumeMode.*should not mount / map unused volumes" \
-		$(E2E) -- -storage.testdriver=../shared/testdriver.yaml
+		$(E2E) -- \
+		-storage.testdriver=$(TESTDRIVER) \
+		--kubeconfig=$(E2EKUBECONFIG)
 
-test-migrating: bin
-	$(GINKGO) $(GINKGO_ARGS) \
-		--focus 'csi.xen-orchestra.marcsi.ch' \
-		--skip 'Disruptive' \
-		--skip "volumeMode.*should not mount / map unused volumes" \
-		$(E2E) -- -storage.testdriver=../migrating/testdriver.yaml
+test-shared: TESTDRIVER=../shared/testdriver.yaml
+test-shared: test
 
+test-migrating: TESTDRIVER=../migrating/testdriver.yaml
+test-migrating: test
 
 # During Development, we can run the test with a specific focus
 # test-directed: bin
+# 	$(check_e2e_kubeconfig)
 # 	$(GINKGO) $(GINKGO_ARGS) \
 # 		--focus 'csi.xen-orchestra.marcsi.ch.*should fail in binding dynamic provisioned PV to PVC' \
 # 		--skip 'Disruptive' \
-# 		$(E2E) -- -storage.testdriver=$(CURDIR)/shared/testdriver.yaml
+# 		$(E2E) -- \
+# 		-storage.testdriver=$(CURDIR)/shared/testdriver.yaml \
+# 		--kubeconfig=$(E2EKUBECONFIG)
 
-
-test: test-shared test-migrating
+test-all: test-shared test-migrating
